# Generated by Django 3.0 on 2022-08-18 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='user',
            new_name='email',
        ),
    ]
